name: ZAP Scan Workflow

on:
  push:
    branches:
      - ESLINT-CHECK   # Change to the branch you want to trigger the scan on

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://apnakycwebuat.rblbank.com/RBL_BANK_UAT_V2/'  # Change this to your application's URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
