name: "API-SCAN" 
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.4.0
        with:
          username​: ​${{ secrets.GHCR_USERNAME }}
          token: ${{ secrets.TEST_SECRECT }}
          docker_name: 'ghcr.io/subharanjan-canaryss/typescript-node-starter:latest'
          format: openapi
          target: 'https://github.com/subharanjan-canaryss/typescript-node-starter'
          rules_file_name: 'check.ts'
          cmd_options: '-a'
