on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_USERNAME }}
          docker_name: 'ghcr.io/subharanjan-canaryss/typescript-node-starter:latest'
          format: openapi
          target: 'https://github.com/subharanjan-canaryss/typescript-node-starter'
          rules_file_name: 'check.ts'
          cmd_options: '-a'
